-- MySQL Script generated by MySQL Workbench
-- 10/10/16 19:42:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`asutus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asutus` (
  `nimi` VARCHAR(45) NOT NULL,
  `ylemasutus` INT NULL,
  `registrikood` INT NOT NULL,
  PRIMARY KEY (`registrikood`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`omanik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`omanik` (
  `isikukood` INT NOT NULL,
  `eesnimi` VARCHAR(45) NULL,
  `perenimi` VARCHAR(45) NULL,
  `teenus` VARCHAR(45) NULL,
  INDEX `fk_omanik_asutus1_idx` (`isikukood` ASC),
  CONSTRAINT `fk_omanik_asutus1`
    FOREIGN KEY (`isikukood`)
    REFERENCES `mydb`.`asutus` (`registrikood`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teenus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teenus` (
  `id` INT NOT NULL,
  `nimi` VARCHAR(45) NOT NULL,
  `kirjeldus` VARCHAR(45) NOT NULL,
  `omanik` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_teenus_omanik1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`omanik` (`isikukood`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kanal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kanal` (
  `teenus` INT NOT NULL,
  `link` VARCHAR(45) NOT NULL,
  `tüüp` VARCHAR(45) NOT NULL,
  `rahulolu` VARCHAR(45) NULL,
  `ajakulu` VARCHAR(45) NULL,
  `kulu` VARCHAR(45) NULL,
  INDEX `fk_kanal_teenus1_idx` (`teenus` ASC),
  CONSTRAINT `fk_kanal_teenus1`
    FOREIGN KEY (`teenus`)
    REFERENCES `mydb`.`teenus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regulatsioon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`regulatsioon` (
  `link` VARCHAR(100) NOT NULL,
  `nimi` VARCHAR(45) NULL,
  `tyyp` VARCHAR(45) NULL,
  PRIMARY KEY (`link`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teenus_has_regulatsioon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teenus_has_regulatsioon` (
  `teenus_id` INT NOT NULL,
  `regulatsioon_link` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`teenus_id`, `regulatsioon_link`),
  INDEX `fk_teenus_has_regulatsioon_regulatsioon1_idx` (`regulatsioon_link` ASC),
  INDEX `fk_teenus_has_regulatsioon_teenus1_idx` (`teenus_id` ASC),
  CONSTRAINT `fk_teenus_has_regulatsioon_teenus1`
    FOREIGN KEY (`teenus_id`)
    REFERENCES `mydb`.`teenus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teenus_has_regulatsioon_regulatsioon1`
    FOREIGN KEY (`regulatsioon_link`)
    REFERENCES `mydb`.`regulatsioon` (`link`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
